### ISSUE TITLE
Generates files but shows error.

### ISSUE THREAD

**Issue by nexxeln** [cake-cutter/cc#7]
**Describe the bug**
I cut the python cake and it generated the files for me but threw an error. `Error: exit status 128`. Also looks like it didn't generate a lot of content of the files? I'm not sure though. All the files are empty except the LICENSE.

**To Reproduce**
1. `cc cut python testing`
2. `What is your name? (John Doe) Shoubhit Dash`
3. `Which operating system are you in? Mac/Linux`
4. `Cutting commands...Error: exit status 128`

**Expected behavior**
Generates files and sends success message.

**Screenshots**
<img width="476" alt="image" src="https://user-images.githubusercontent.com/95541290/174423716-72313de6-9090-4eb0-b325-c428bda9d192.png">
![files](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/Code_Kl4pA1JuDg.gif)

**Desktop (please complete the following information):**
 - OS: WSL2 Ubuntu

**Comment by Dhravya** [comment]
> Also looks like it didn't generate a lot of content of the files?

Yep. It doesn't generate a lot of contents as of right now, but the [Python cake](https://github.com/cake-cutter/cakes/tree/main/python) can be updated to be more powerful. 

As for the error, what binary do you use for python, is it `python` or `python3`?
I'm pretty sure the reason for this error is because the commands couldn't be run, which is probably because the binary couldn't be found?

For contributors: You can update the Python Cake to fill in the contents

@kekda-py , I think the errors thrown should be shown to the user for easier bug fixes `Cutting commands...Error: exit status 128`

For this particular issue, maybe the python cake should ask for the binary name instead of mac/windows/linux, don't you think?

**Comment by nexxeln** [comment]
In mac/linux its always python3, what are you asking the OS for then if not to run python3 commands?

**Comment by Dhravya** [comment]
asking of the OS is to run the python3 commands, yes, check issue #5 

Hmm, if it's not because of the binaries found, I wonder what it could be....

Do you think any of these commands failed to execute?

```toml
"python3 -m venv env" = '''
{{if eq (index . "os") "Windows"}}
  false
{{else}}
  true
{{end}}
'''
"git init" = "true"
"git add ." = "true"
"git commit -m 'Initial app created using cakecutter'" = "true"
```

**Comment by nexxeln** [comment]
ah interesting, in debian/ubuntu i need a separate package to create a venv. let me try and see if it works now.

**Comment by nexxeln** [comment]
nope still same error.

**Comment by kekda-py** [comment]
I fixed this issue tomorrow

**Comment by kekda-py** [comment]
The git commit command was causing it

**Comment by kekda-py** [comment]
https://github.com/cake-cutter/cc/commit/198dbfa1c43d4cd037fd5d7221b7b2cf3c120f94 in this commit

**Comment by kekda-py** [comment]
> @kekda-py , I think the errors thrown should be shown to the user for easier bug fixes `Cutting commands...Error: exit status 128`

Say that to google lmao. I didn't made those errors

**Comment by kekda-py** [comment]
> @kekda-py , I think the errors thrown should be shown to the user for easier bug fixes `Cutting commands...Error: exit status 128`

It does... thats an error returned by go.

**Comment by nexxeln** [comment]
Cool! works now that I reinstalled.
